// This file is auto-generated by Lovable. Do not modify it.

import type { OAuthProvider } from "@lovable.dev/cloud-auth-js";
import { supabase } from "../supabase/client";

type SignInOptions = {
  redirect_uri?: string;
  extraParams?: Record<string, string>;
};

export const lovable = {
  auth: {
    signInWithOAuth: async (provider: OAuthProvider, opts?: SignInOptions) => {
      if (provider !== "google") {
        return {
          error: new Error(`OAuth provider "${provider}" is not configured for this application.`),
        };
      }

      const options = {
        redirectTo: opts?.redirect_uri ?? window.location.origin,
        ...(opts?.extraParams ? { queryParams: opts.extraParams } : {}),
      };
      const result = await supabase.auth.signInWithOAuth({
        provider,
        options,
      });

      if (result.error) {
        return { error: result.error };
      }
      return { error: null, redirected: Boolean(result.data.url) };
    },
  },
};
