/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthIndexRouteImport } from './routes/auth.index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthVerifyRouteImport } from './routes/auth.verify'
import { Route as FounderIndexRouteImport } from './routes/founder.index'
import { Route as FounderApplicationsRouteImport } from './routes/founder.applications'
import { Route as FounderMembershipRouteImport } from './routes/founder.membership'
import { Route as FounderMessagesRouteImport } from './routes/founder.messages'
import { Route as FounderProfileRouteImport } from './routes/founder.profile'
import { Route as FounderReadinessRouteImport } from './routes/founder.readiness'
import { Route as FounderWorkspaceRouteImport } from './routes/founder.workspace'
import { Route as OnboardingFounderRouteImport } from './routes/onboarding.founder'
import { Route as OnboardingPartnerRouteImport } from './routes/onboarding.partner'
import { Route as PartnerIndexRouteImport } from './routes/partner.index'
import { Route as PartnerAnalyticsRouteImport } from './routes/partner.analytics'
import { Route as PartnerApplicationsRouteImport } from './routes/partner.applications'
import { Route as PartnerMembershipRouteImport } from './routes/partner.membership'
import { Route as PartnerMessagesRouteImport } from './routes/partner.messages'
import { Route as PartnerOpportunitiesRouteImport } from './routes/partner.opportunities'
import { Route as PartnerPostRouteImport } from './routes/partner.post'
import { Route as PartnerProfileRouteImport } from './routes/partner.profile'
import { Route as AuthFounderLoginRouteImport } from './routes/auth.founder.login'
import { Route as AuthFounderSignupRouteImport } from './routes/auth.founder.signup'
import { Route as AuthPartnerLoginRouteImport } from './routes/auth.partner.login'
import { Route as AuthPartnerSignupRouteImport } from './routes/auth.partner.signup'
import { Route as FounderOpportunitiesIndexRouteImport } from './routes/founder.opportunities.index'
import { Route as FounderOpportunitiesOppIdRouteImport } from './routes/founder.opportunities.$oppId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/auth/verify',
  path: '/auth/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderIndexRoute = FounderIndexRouteImport.update({
  id: '/founder/',
  path: '/founder/',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderApplicationsRoute = FounderApplicationsRouteImport.update({
  id: '/founder/applications',
  path: '/founder/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderMembershipRoute = FounderMembershipRouteImport.update({
  id: '/founder/membership',
  path: '/founder/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderMessagesRoute = FounderMessagesRouteImport.update({
  id: '/founder/messages',
  path: '/founder/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderProfileRoute = FounderProfileRouteImport.update({
  id: '/founder/profile',
  path: '/founder/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderReadinessRoute = FounderReadinessRouteImport.update({
  id: '/founder/readiness',
  path: '/founder/readiness',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderWorkspaceRoute = FounderWorkspaceRouteImport.update({
  id: '/founder/workspace',
  path: '/founder/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingFounderRoute = OnboardingFounderRouteImport.update({
  id: '/onboarding/founder',
  path: '/onboarding/founder',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingPartnerRoute = OnboardingPartnerRouteImport.update({
  id: '/onboarding/partner',
  path: '/onboarding/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerIndexRoute = PartnerIndexRouteImport.update({
  id: '/partner/',
  path: '/partner/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerAnalyticsRoute = PartnerAnalyticsRouteImport.update({
  id: '/partner/analytics',
  path: '/partner/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerApplicationsRoute = PartnerApplicationsRouteImport.update({
  id: '/partner/applications',
  path: '/partner/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerMembershipRoute = PartnerMembershipRouteImport.update({
  id: '/partner/membership',
  path: '/partner/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerMessagesRoute = PartnerMessagesRouteImport.update({
  id: '/partner/messages',
  path: '/partner/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerOpportunitiesRoute = PartnerOpportunitiesRouteImport.update({
  id: '/partner/opportunities',
  path: '/partner/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerPostRoute = PartnerPostRouteImport.update({
  id: '/partner/post',
  path: '/partner/post',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerProfileRoute = PartnerProfileRouteImport.update({
  id: '/partner/profile',
  path: '/partner/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthFounderLoginRoute = AuthFounderLoginRouteImport.update({
  id: '/auth/founder/login',
  path: '/auth/founder/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthFounderSignupRoute = AuthFounderSignupRouteImport.update({
  id: '/auth/founder/signup',
  path: '/auth/founder/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPartnerLoginRoute = AuthPartnerLoginRouteImport.update({
  id: '/auth/partner/login',
  path: '/auth/partner/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPartnerSignupRoute = AuthPartnerSignupRouteImport.update({
  id: '/auth/partner/signup',
  path: '/auth/partner/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderOpportunitiesIndexRoute =
  FounderOpportunitiesIndexRouteImport.update({
    id: '/founder/opportunities/',
    path: '/founder/opportunities/',
    getParentRoute: () => rootRouteImport,
  } as any)
const FounderOpportunitiesOppIdRoute =
  FounderOpportunitiesOppIdRouteImport.update({
    id: '/founder/opportunities/$oppId',
    path: '/founder/opportunities/$oppId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/founder/applications': typeof FounderApplicationsRoute
  '/founder/membership': typeof FounderMembershipRoute
  '/founder/messages': typeof FounderMessagesRoute
  '/founder/profile': typeof FounderProfileRoute
  '/founder/readiness': typeof FounderReadinessRoute
  '/founder/workspace': typeof FounderWorkspaceRoute
  '/onboarding/founder': typeof OnboardingFounderRoute
  '/onboarding/partner': typeof OnboardingPartnerRoute
  '/partner/analytics': typeof PartnerAnalyticsRoute
  '/partner/applications': typeof PartnerApplicationsRoute
  '/partner/membership': typeof PartnerMembershipRoute
  '/partner/messages': typeof PartnerMessagesRoute
  '/partner/opportunities': typeof PartnerOpportunitiesRoute
  '/partner/post': typeof PartnerPostRoute
  '/partner/profile': typeof PartnerProfileRoute
  '/auth/': typeof AuthIndexRoute
  '/founder/': typeof FounderIndexRoute
  '/partner/': typeof PartnerIndexRoute
  '/auth/founder/login': typeof AuthFounderLoginRoute
  '/auth/founder/signup': typeof AuthFounderSignupRoute
  '/auth/partner/login': typeof AuthPartnerLoginRoute
  '/auth/partner/signup': typeof AuthPartnerSignupRoute
  '/founder/opportunities/$oppId': typeof FounderOpportunitiesOppIdRoute
  '/founder/opportunities/': typeof FounderOpportunitiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/founder/applications': typeof FounderApplicationsRoute
  '/founder/membership': typeof FounderMembershipRoute
  '/founder/messages': typeof FounderMessagesRoute
  '/founder/profile': typeof FounderProfileRoute
  '/founder/readiness': typeof FounderReadinessRoute
  '/founder/workspace': typeof FounderWorkspaceRoute
  '/onboarding/founder': typeof OnboardingFounderRoute
  '/onboarding/partner': typeof OnboardingPartnerRoute
  '/partner/analytics': typeof PartnerAnalyticsRoute
  '/partner/applications': typeof PartnerApplicationsRoute
  '/partner/membership': typeof PartnerMembershipRoute
  '/partner/messages': typeof PartnerMessagesRoute
  '/partner/opportunities': typeof PartnerOpportunitiesRoute
  '/partner/post': typeof PartnerPostRoute
  '/partner/profile': typeof PartnerProfileRoute
  '/auth': typeof AuthIndexRoute
  '/founder': typeof FounderIndexRoute
  '/partner': typeof PartnerIndexRoute
  '/auth/founder/login': typeof AuthFounderLoginRoute
  '/auth/founder/signup': typeof AuthFounderSignupRoute
  '/auth/partner/login': typeof AuthPartnerLoginRoute
  '/auth/partner/signup': typeof AuthPartnerSignupRoute
  '/founder/opportunities/$oppId': typeof FounderOpportunitiesOppIdRoute
  '/founder/opportunities': typeof FounderOpportunitiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/founder/applications': typeof FounderApplicationsRoute
  '/founder/membership': typeof FounderMembershipRoute
  '/founder/messages': typeof FounderMessagesRoute
  '/founder/profile': typeof FounderProfileRoute
  '/founder/readiness': typeof FounderReadinessRoute
  '/founder/workspace': typeof FounderWorkspaceRoute
  '/onboarding/founder': typeof OnboardingFounderRoute
  '/onboarding/partner': typeof OnboardingPartnerRoute
  '/partner/analytics': typeof PartnerAnalyticsRoute
  '/partner/applications': typeof PartnerApplicationsRoute
  '/partner/membership': typeof PartnerMembershipRoute
  '/partner/messages': typeof PartnerMessagesRoute
  '/partner/opportunities': typeof PartnerOpportunitiesRoute
  '/partner/post': typeof PartnerPostRoute
  '/partner/profile': typeof PartnerProfileRoute
  '/auth/': typeof AuthIndexRoute
  '/founder/': typeof FounderIndexRoute
  '/partner/': typeof PartnerIndexRoute
  '/auth/founder/login': typeof AuthFounderLoginRoute
  '/auth/founder/signup': typeof AuthFounderSignupRoute
  '/auth/partner/login': typeof AuthPartnerLoginRoute
  '/auth/partner/signup': typeof AuthPartnerSignupRoute
  '/founder/opportunities/$oppId': typeof FounderOpportunitiesOppIdRoute
  '/founder/opportunities/': typeof FounderOpportunitiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/verify'
    | '/founder/applications'
    | '/founder/membership'
    | '/founder/messages'
    | '/founder/profile'
    | '/founder/readiness'
    | '/founder/workspace'
    | '/onboarding/founder'
    | '/onboarding/partner'
    | '/partner/analytics'
    | '/partner/applications'
    | '/partner/membership'
    | '/partner/messages'
    | '/partner/opportunities'
    | '/partner/post'
    | '/partner/profile'
    | '/auth/'
    | '/founder/'
    | '/partner/'
    | '/auth/founder/login'
    | '/auth/founder/signup'
    | '/auth/partner/login'
    | '/auth/partner/signup'
    | '/founder/opportunities/$oppId'
    | '/founder/opportunities/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/verify'
    | '/founder/applications'
    | '/founder/membership'
    | '/founder/messages'
    | '/founder/profile'
    | '/founder/readiness'
    | '/founder/workspace'
    | '/onboarding/founder'
    | '/onboarding/partner'
    | '/partner/analytics'
    | '/partner/applications'
    | '/partner/membership'
    | '/partner/messages'
    | '/partner/opportunities'
    | '/partner/post'
    | '/partner/profile'
    | '/auth'
    | '/founder'
    | '/partner'
    | '/auth/founder/login'
    | '/auth/founder/signup'
    | '/auth/partner/login'
    | '/auth/partner/signup'
    | '/founder/opportunities/$oppId'
    | '/founder/opportunities'
  id:
    | '__root__'
    | '/'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/verify'
    | '/founder/applications'
    | '/founder/membership'
    | '/founder/messages'
    | '/founder/profile'
    | '/founder/readiness'
    | '/founder/workspace'
    | '/onboarding/founder'
    | '/onboarding/partner'
    | '/partner/analytics'
    | '/partner/applications'
    | '/partner/membership'
    | '/partner/messages'
    | '/partner/opportunities'
    | '/partner/post'
    | '/partner/profile'
    | '/auth/'
    | '/founder/'
    | '/partner/'
    | '/auth/founder/login'
    | '/auth/founder/signup'
    | '/auth/partner/login'
    | '/auth/partner/signup'
    | '/founder/opportunities/$oppId'
    | '/founder/opportunities/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
  FounderApplicationsRoute: typeof FounderApplicationsRoute
  FounderMembershipRoute: typeof FounderMembershipRoute
  FounderMessagesRoute: typeof FounderMessagesRoute
  FounderProfileRoute: typeof FounderProfileRoute
  FounderReadinessRoute: typeof FounderReadinessRoute
  FounderWorkspaceRoute: typeof FounderWorkspaceRoute
  OnboardingFounderRoute: typeof OnboardingFounderRoute
  OnboardingPartnerRoute: typeof OnboardingPartnerRoute
  PartnerAnalyticsRoute: typeof PartnerAnalyticsRoute
  PartnerApplicationsRoute: typeof PartnerApplicationsRoute
  PartnerMembershipRoute: typeof PartnerMembershipRoute
  PartnerMessagesRoute: typeof PartnerMessagesRoute
  PartnerOpportunitiesRoute: typeof PartnerOpportunitiesRoute
  PartnerPostRoute: typeof PartnerPostRoute
  PartnerProfileRoute: typeof PartnerProfileRoute
  AuthIndexRoute: typeof AuthIndexRoute
  FounderIndexRoute: typeof FounderIndexRoute
  PartnerIndexRoute: typeof PartnerIndexRoute
  AuthFounderLoginRoute: typeof AuthFounderLoginRoute
  AuthFounderSignupRoute: typeof AuthFounderSignupRoute
  AuthPartnerLoginRoute: typeof AuthPartnerLoginRoute
  AuthPartnerSignupRoute: typeof AuthPartnerSignupRoute
  FounderOpportunitiesOppIdRoute: typeof FounderOpportunitiesOppIdRoute
  FounderOpportunitiesIndexRoute: typeof FounderOpportunitiesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/auth/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder/': {
      id: '/founder/'
      path: '/founder'
      fullPath: '/founder/'
      preLoaderRoute: typeof FounderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder/applications': {
      id: '/founder/applications'
      path: '/founder/applications'
      fullPath: '/founder/applications'
      preLoaderRoute: typeof FounderApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder/membership': {
      id: '/founder/membership'
      path: '/founder/membership'
      fullPath: '/founder/membership'
      preLoaderRoute: typeof FounderMembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder/messages': {
      id: '/founder/messages'
      path: '/founder/messages'
      fullPath: '/founder/messages'
      preLoaderRoute: typeof FounderMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder/profile': {
      id: '/founder/profile'
      path: '/founder/profile'
      fullPath: '/founder/profile'
      preLoaderRoute: typeof FounderProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder/readiness': {
      id: '/founder/readiness'
      path: '/founder/readiness'
      fullPath: '/founder/readiness'
      preLoaderRoute: typeof FounderReadinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder/workspace': {
      id: '/founder/workspace'
      path: '/founder/workspace'
      fullPath: '/founder/workspace'
      preLoaderRoute: typeof FounderWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/founder': {
      id: '/onboarding/founder'
      path: '/onboarding/founder'
      fullPath: '/onboarding/founder'
      preLoaderRoute: typeof OnboardingFounderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/partner': {
      id: '/onboarding/partner'
      path: '/onboarding/partner'
      fullPath: '/onboarding/partner'
      preLoaderRoute: typeof OnboardingPartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/': {
      id: '/partner/'
      path: '/partner'
      fullPath: '/partner/'
      preLoaderRoute: typeof PartnerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/analytics': {
      id: '/partner/analytics'
      path: '/partner/analytics'
      fullPath: '/partner/analytics'
      preLoaderRoute: typeof PartnerAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/applications': {
      id: '/partner/applications'
      path: '/partner/applications'
      fullPath: '/partner/applications'
      preLoaderRoute: typeof PartnerApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/membership': {
      id: '/partner/membership'
      path: '/partner/membership'
      fullPath: '/partner/membership'
      preLoaderRoute: typeof PartnerMembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/messages': {
      id: '/partner/messages'
      path: '/partner/messages'
      fullPath: '/partner/messages'
      preLoaderRoute: typeof PartnerMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/opportunities': {
      id: '/partner/opportunities'
      path: '/partner/opportunities'
      fullPath: '/partner/opportunities'
      preLoaderRoute: typeof PartnerOpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/post': {
      id: '/partner/post'
      path: '/partner/post'
      fullPath: '/partner/post'
      preLoaderRoute: typeof PartnerPostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/profile': {
      id: '/partner/profile'
      path: '/partner/profile'
      fullPath: '/partner/profile'
      preLoaderRoute: typeof PartnerProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/founder/login': {
      id: '/auth/founder/login'
      path: '/auth/founder/login'
      fullPath: '/auth/founder/login'
      preLoaderRoute: typeof AuthFounderLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/founder/signup': {
      id: '/auth/founder/signup'
      path: '/auth/founder/signup'
      fullPath: '/auth/founder/signup'
      preLoaderRoute: typeof AuthFounderSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/partner/login': {
      id: '/auth/partner/login'
      path: '/auth/partner/login'
      fullPath: '/auth/partner/login'
      preLoaderRoute: typeof AuthPartnerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/partner/signup': {
      id: '/auth/partner/signup'
      path: '/auth/partner/signup'
      fullPath: '/auth/partner/signup'
      preLoaderRoute: typeof AuthPartnerSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder/opportunities/': {
      id: '/founder/opportunities/'
      path: '/founder/opportunities'
      fullPath: '/founder/opportunities/'
      preLoaderRoute: typeof FounderOpportunitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder/opportunities/$oppId': {
      id: '/founder/opportunities/$oppId'
      path: '/founder/opportunities/$oppId'
      fullPath: '/founder/opportunities/$oppId'
      preLoaderRoute: typeof FounderOpportunitiesOppIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthVerifyRoute: AuthVerifyRoute,
  FounderApplicationsRoute: FounderApplicationsRoute,
  FounderMembershipRoute: FounderMembershipRoute,
  FounderMessagesRoute: FounderMessagesRoute,
  FounderProfileRoute: FounderProfileRoute,
  FounderReadinessRoute: FounderReadinessRoute,
  FounderWorkspaceRoute: FounderWorkspaceRoute,
  OnboardingFounderRoute: OnboardingFounderRoute,
  OnboardingPartnerRoute: OnboardingPartnerRoute,
  PartnerAnalyticsRoute: PartnerAnalyticsRoute,
  PartnerApplicationsRoute: PartnerApplicationsRoute,
  PartnerMembershipRoute: PartnerMembershipRoute,
  PartnerMessagesRoute: PartnerMessagesRoute,
  PartnerOpportunitiesRoute: PartnerOpportunitiesRoute,
  PartnerPostRoute: PartnerPostRoute,
  PartnerProfileRoute: PartnerProfileRoute,
  AuthIndexRoute: AuthIndexRoute,
  FounderIndexRoute: FounderIndexRoute,
  PartnerIndexRoute: PartnerIndexRoute,
  AuthFounderLoginRoute: AuthFounderLoginRoute,
  AuthFounderSignupRoute: AuthFounderSignupRoute,
  AuthPartnerLoginRoute: AuthPartnerLoginRoute,
  AuthPartnerSignupRoute: AuthPartnerSignupRoute,
  FounderOpportunitiesOppIdRoute: FounderOpportunitiesOppIdRoute,
  FounderOpportunitiesIndexRoute: FounderOpportunitiesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
